name: vis-env
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - pip:
      - -r file:requirements.txt
      - isort == 5.0.4
      - yapf == 0.3.0
      - flake8 == 3.8.4
      - flake8-quotes == 3.2.0
