name: vis-env
channels:
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - pip:
      - isort == 5.0.4
      - networkx
      - flake8
      - flake8-quotes
      - deprecated
      - sklearn
      - yapf
      - Flask
      - protobuf
