package(default_visibility = ["//visibility:public"])

py_test(
    name = "test_d3_graph",
    srcs = ["test_d3_graph.py"],
    deps = [
    ],
)

py_test(
    name = "tf_test_d3_graph",
    srcs = ["tf_test_d3_graph.py"],
    deps = [
    ],
)
