package(
    default_visibility = ["//visibility:public"],
)

load("//sdk2:sdk2.bzl", "lt_html_library")

lt_html_library(
    name = "d3_graph",
    srcs = ["d3_graph.html"],
    deps = [
        "//sdk2/visuals/javascript_tests/static:d3_graph_js",
    ],
)
